import { StyleSheet, Platform, Dimensions } from 'react-native';
import { colors } from '../../../theme/colors';

const { width: SCREEN_WIDTH } = Dimensions.get("window");

export const styles = StyleSheet.create({
   container: { flex: 1, backgroundColor: "#000" },
   topHeader: {
      paddingVertical: 15,
      paddingHorizontal: 20,
      borderBottomWidth: 1,
      borderColor: "rgba(255,255,255,0.05)",
   },
   headerRow: { flexDirection: "row", alignItems: "center" },
   backBtn: {
      width: 40,
      height: 40,
      borderRadius: 20,
      backgroundColor: "rgba(255,255,255,0.05)",
      justifyContent: "center",
      alignItems: "center",
   },
   greetingText: {
      color: "rgba(255,255,255,0.4)",
      fontSize: 12,
      fontWeight: "900",
      letterSpacing: 1,
   },
   hospitalName: {
      color: "#FFF",
      fontSize: 18,
      fontWeight: "900",
      marginTop: 2,
   },
   mainWrapper: { flex: 1 },
   contentArea: { flex: 1 },
   stepBase: { flex: 1, padding: 24 },
   stepInlineHeader: {
      flexDirection: "row",
      alignItems: "flex-start",
      marginBottom: 14,
      gap: 12,
   },
   stepInlineBack: {
      width: 44,
      height: 44,
      borderRadius: 16,
      backgroundColor: "#1A1A1A",
      justifyContent: "center",
      alignItems: "center",
      borderWidth: 1,
      borderColor: "rgba(255,255,255,0.1)",
   },
   stepInlineTextCol: {
      flex: 1,
      minWidth: 0,
      paddingTop: 2,
   },
   stepInlineLabel: {
      color: "rgba(255,255,255,0.45)",
      fontSize: 13,
      fontWeight: "800",
      letterSpacing: 1.2,
      marginBottom: 6,
      textTransform: "uppercase",
   },
   stepInlineTitle: {
      color: "#FFF",
      fontSize: 22,
      fontWeight: "900",
      letterSpacing: -0.3,
      lineHeight: 28,
   },
   stepInlineSub: {
      color: "rgba(255,255,255,0.45)",
      fontSize: 13,
      fontWeight: "500",
      marginTop: 2,
   },
   stepSectionHeading: {
      color: "rgba(255,255,255,0.9)",
      fontSize: 17,
      fontWeight: "800",
      marginBottom: 14,
   },
   divider: {
      height: 1,
      backgroundColor: "rgba(255,255,255,0.05)",
      marginVertical: 15,
   },
   bigActionBtn: {
      height: 64,
      borderRadius: 20,
      backgroundColor: colors.secondary,
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "center",
      gap: 12,
      marginTop: 20,
   },
   bigActionText: {
      color: "#FFF",
      fontSize: 16,
      fontWeight: "900",
      letterSpacing: 1,
   },
   assignmentEnRouteFab: {
      position: "absolute",
      bottom: 200,
      right: 16,
      zIndex: 5,
      minWidth: 112,
      paddingVertical: 12,
      paddingHorizontal: 14,
      borderRadius: 28,
      backgroundColor: colors.primary,
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "center",
      gap: 8,
      shadowColor: "#000",
      shadowOpacity: 0.35,
      shadowRadius: 8,
      elevation: 6,
   },
   assignmentEnRouteFabText: {
      color: "#FFF",
      fontSize: 14,
      fontWeight: "800",
   },
   assignmentNavBtn: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 10,
      backgroundColor: colors.secondary,
      paddingHorizontal: 20,
      paddingVertical: 14,
      borderRadius: 16,
      borderWidth: 1,
      borderColor: colors.secondary + '40',
   },
   assignmentNavBtnText: {
      color: '#000',
      fontSize: 15,
      fontWeight: '900',
   },
   standbyView: {
      flex: 1,
      justifyContent: "center",
      alignItems: "center",
      padding: 30,
   },
   radarWrapper: {
      width: 200,
      height: 200,
      justifyContent: "center",
      alignItems: "center",
      marginBottom: 40,
   },
   radarCircle: {
      position: "absolute",
      width: 200,
      height: 200,
      borderRadius: 100,
      borderWidth: 2,
      borderColor: colors.secondary,
      backgroundColor: colors.secondary + "10",
   },
   standbyText: {
      color: "#FFF",
      fontSize: 18,
      fontWeight: "900",
      textAlign: "center",
   },
   standbySub: {
      color: "rgba(255,255,255,0.4)",
      fontSize: 14,
      textAlign: "center",
      marginTop: 10,
      lineHeight: 20,
   },
   assignmentPopup: {
      position: "absolute",
      bottom: 20,
      left: 20,
      right: 20,
      backgroundColor: "#1A1A1A",
      borderRadius: 24,
      padding: 20,
      borderWidth: 1,
      borderColor: colors.secondary + "40",
   },
   assignRow: {
      flexDirection: "row",
      alignItems: "center",
      gap: 10,
      marginBottom: 10,
   },
   priorityDot: {
      width: 8,
      height: 8,
      borderRadius: 4,
      backgroundColor: colors.primary,
   },
   assignHeader: {
      color: "rgba(255,255,255,0.5)",
      fontSize: 12,
      fontWeight: "900",
      letterSpacing: 1,
   },
   assignType: { color: "#FFF", fontSize: 20, fontWeight: "900" },
   assignLoc: { color: "rgba(255,255,255,0.4)", fontSize: 14, marginTop: 4 },
   assignAction: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      marginTop: 20,
      backgroundColor: colors.secondary,
      padding: 15,
      borderRadius: 15,
   },
   assignActionText: { color: "#FFF", fontSize: 14, fontWeight: "900" },
   victimStripReceptionWrap: {
      marginTop: 14,
      paddingHorizontal: 0,
      paddingTop: 8,
      paddingBottom: 4,
      backgroundColor: "transparent",
   },
   victimStripGlobalWrap: {
      paddingHorizontal: 12,
      paddingTop: 10,
      paddingBottom: 6,
      backgroundColor: colors.mainBackground,
   },
   terrainPhotosStrip: {
      paddingHorizontal: 16,
      paddingTop: 8,
      paddingBottom: 10,
      borderBottomWidth: 1,
      borderBottomColor: "rgba(255,255,255,0.06)",
      backgroundColor: "rgba(0,0,0,0.35)",
   },
   terrainPhotosStripHeader: {
      flexDirection: "row",
      alignItems: "flex-start",
      gap: 8,
      marginBottom: 10,
   },
   terrainPhotosStripTitle: {
      color: "rgba(255,255,255,0.85)",
      fontSize: 13,
      fontWeight: "800",
      letterSpacing: 0.8,
   },
   terrainPhotosStripHint: {
      color: "rgba(255,255,255,0.45)",
      fontSize: 11,
      fontWeight: "600",
      marginTop: 4,
      lineHeight: 15,
   },
   terrainPhotosScroll: {
      flexDirection: "row",
      alignItems: "center",
      gap: 10,
      paddingRight: 8,
   },
   terrainPhotoThumb: {
      width: 64,
      height: 64,
      borderRadius: 12,
      backgroundColor: "#1A1A1A",
   },
   terrainPhotoActions: {
      flexDirection: "row",
      alignItems: "center",
      gap: 8,
   },
   terrainPhotoAddBtn: {
      width: 76,
      height: 64,
      borderRadius: 12,
      borderWidth: 1.5,
      borderColor: colors.secondary + "35",
      borderStyle: "dashed",
      alignItems: "center",
      justifyContent: "center",
      backgroundColor: colors.secondary + "08",
   },
   terrainPhotoAddBtnPrimary: {
      borderStyle: "solid",
      borderColor: colors.secondary + "AA",
      backgroundColor: colors.secondary + "18",
   },
   terrainPhotoAddBtnSecondary: {
      borderColor: "rgba(255,255,255,0.12)",
      backgroundColor: "rgba(255,255,255,0.04)",
   },
   terrainPhotoAddText: {
      color: colors.secondary,
      fontSize: 11,
      fontWeight: "800",
      marginTop: 2,
   },
   terrainPhotoAddTextSecondary: {
      color: "rgba(255,255,255,0.5)",
      fontSize: 10,
      fontWeight: "700",
      marginTop: 2,
   },
   victimContactStrip: {
      backgroundColor: "#161616",
      borderRadius: 16,
      padding: 12,
      borderWidth: 1,
      borderColor: "rgba(255,255,255,0.12)",
   },
   victimContactStripTitle: {
      color: "rgba(255,255,255,0.5)",
      fontSize: 11,
      fontWeight: "900",
      letterSpacing: 0.8,
      marginBottom: 10,
   },
   victimContactRow: { flexDirection: "row", gap: 8, alignItems: "stretch" },
   victimContactChip: {
      flex: 1,
      flexDirection: "column",
      alignItems: "center",
      justifyContent: "center",
      gap: 4,
      paddingVertical: 10,
      paddingHorizontal: 6,
      borderRadius: 12,
      backgroundColor: "#222",
      borderWidth: 1,
      borderColor: "rgba(255,255,255,0.08)",
      minHeight: 72,
   },
   victimContactChipDisabled: { opacity: 0.45 },
   victimContactChipText: { color: "#FFF", fontSize: 11, fontWeight: "800", textAlign: "center" },
   victimContactChipTextDisabled: { color: "rgba(255,255,255,0.35)" },
   victimContactHint: {
      color: "rgba(255,255,255,0.35)",
      fontSize: 11,
      marginTop: 10,
      lineHeight: 15,
   },
   receptionView: { flex: 1, flexDirection: "column", padding: 0 },
   receptionBottomPanel: { flex: 1, minHeight: 180 },
   receptionScroll: { flex: 1 },
   floatingBackSignalement: {
      position: "absolute",
      left: 12,
      zIndex: 20,
      width: 44,
      height: 44,
      borderRadius: 16,
      backgroundColor: "rgba(0,0,0,0.55)",
      justifyContent: "center",
      alignItems: "center",
      borderWidth: 1,
      borderColor: "rgba(255,255,255,0.12)",
   },
   mapFullscreenEntryBtn: {
      position: "absolute",
      right: 12,
      zIndex: 21,
      width: 44,
      height: 44,
      borderRadius: 16,
      backgroundColor: "rgba(0,0,0,0.55)",
      justifyContent: "center",
      alignItems: "center",
      borderWidth: 1,
      borderColor: "rgba(255,255,255,0.12)",
   },
   mapFullscreenEntryBtnAssignment: {
      position: "absolute",
      top: 12,
      right: 12,
      zIndex: 21,
      width: 44,
      height: 44,
      borderRadius: 16,
      backgroundColor: "rgba(0,0,0,0.55)",
      justifyContent: "center",
      alignItems: "center",
      borderWidth: 1,
      borderColor: "rgba(255,255,255,0.12)",
   },
   detailMissionType: { color: "#FFF", fontSize: 18, fontWeight: "800" },
   detailBox: {
      flex: 1,
      backgroundColor: "#111",
      borderRadius: 30,
      padding: 25,
      borderWidth: 1,
      borderColor: "rgba(255,255,255,0.05)",
   },
   receptionHeaderStrip: {
      flexDirection: "row",
      alignItems: "center",
      gap: 15,
      marginBottom: 10,
   },
   detailLabel: {
      color: "rgba(255,255,255,0.3)",
      fontSize: 12,
      fontWeight: "900",
      letterSpacing: 1.5,
      marginBottom: 4,
   },
   detailVal: { color: "#FFF", fontSize: 18, fontWeight: "800" },
   detailDesc: { color: "rgba(255,255,255,0.7)", fontSize: 15, lineHeight: 24 },
   priorityStatusText: { color: "#FFF", fontSize: 14, fontWeight: "700" },
   receptionMapWrapper: {
      flex: 1,
      minHeight: 220,
      width: "100%",
      backgroundColor: "#1A1A1A",
      overflow: "hidden",
      borderBottomWidth: 1,
      borderColor: "rgba(255,255,255,0.05)",
   },
   receptionMap: {
      flex: 1,
   },
   mapDistOverlay: {
      position: "absolute",
      bottom: 20,
      right: 20,
      backgroundColor: "rgba(0,0,0,0.8)",
      paddingHorizontal: 12,
      paddingVertical: 8,
      borderRadius: 12,
      flexDirection: "row",
      alignItems: "center",
      gap: 6,
      borderWidth: 1,
      borderColor: "rgba(255,255,255,0.1)",
   },
   mapDistText: {
      color: "#FFF",
      fontSize: 12,
      fontWeight: "800",
   },
   stickySwipeWrapper: {
      position: "absolute",
      bottom: 0,
      left: 0,
      right: 0,
      paddingHorizontal: 24,
      paddingBottom: 24,
      paddingTop: 20,
      backgroundColor: "rgba(0,0,0,0.7)",
   },
   swipeContainer: {
      height: 72,
      width: "100%",
      backgroundColor: "#1A1A1A",
      borderRadius: 36,
      padding: 4,
      justifyContent: "center",
      overflow: "hidden",
      borderWidth: 1,
      borderColor: "rgba(255,255,255,0.1)",
   },
   swipeBackground: {
      position: "absolute",
      left: 0,
      right: 0,
      flexDirection: "row",
      justifyContent: "center",
      alignItems: "center",
      gap: 12,
   },
   swipeText: {
      color: "rgba(255,255,255,0.4)",
      fontSize: 15,
      fontWeight: "800",
   },
   swipeThumb: {
      width: 64,
      height: 64,
      borderRadius: 32,
      backgroundColor: colors.secondary,
      justifyContent: "center",
      alignItems: "center",
   },
   trackingMapWrapper: { flex: 1, borderRadius: 0, overflow: "hidden" },
   trackingMap: { flex: 1 },
   markerHalo: {
      width: 40,
      height: 40,
      borderRadius: 20,
      backgroundColor: "rgba(255,59,48,0.2)",
      justifyContent: "center",
      alignItems: "center",
      borderWidth: 2,
      borderColor: colors.primary,
   },
   victimMarker: {
      width: 36,
      height: 36,
      borderRadius: 18,
      backgroundColor: colors.primary,
      justifyContent: "center",
      alignItems: "center",
      borderWidth: 2,
      borderColor: "#FFFFFF",
      shadowColor: colors.primary,
      shadowOpacity: 0.5,
      shadowRadius: 8,
      shadowOffset: { width: 0, height: 2 },
      elevation: 6,
   },
   urgentisteMarker: {
      width: 36,
      height: 36,
      borderRadius: 18,
      backgroundColor: colors.secondary,
      justifyContent: "center",
      alignItems: "center",
      borderWidth: 2,
      borderColor: "#FFFFFF",
      shadowColor: colors.secondary,
      shadowOpacity: 0.5,
      shadowRadius: 8,
      shadowOffset: { width: 0, height: 2 },
      elevation: 6,
   },
   hospitalMarker: {
      width: 36,
      height: 36,
      borderRadius: 18,
      backgroundColor: "#2E7D32",
      justifyContent: "center",
      alignItems: "center",
      borderWidth: 2,
      borderColor: "#FFFFFF",
      shadowColor: "#2E7D32",
      shadowOpacity: 0.5,
      shadowRadius: 8,
      shadowOffset: { width: 0, height: 2 },
      elevation: 6,
   },
   assignmentBottomPanel: {
      backgroundColor: colors.mainBackground,
      borderTopLeftRadius: 20,
      borderTopRightRadius: 20,
      marginTop: -16,
      paddingTop: 4,
   },
   assignmentStructureCard: {
      marginHorizontal: 20,
      marginVertical: 12,
      backgroundColor: 'rgba(255,255,255,0.05)',
      borderRadius: 16,
      padding: 16,
      borderWidth: 1,
      borderColor: 'rgba(255,255,255,0.08)',
   },
   structureIconBox: {
      width: 44,
      height: 44,
      borderRadius: 14,
      backgroundColor: colors.secondary + '15',
      justifyContent: 'center',
      alignItems: 'center',
   },
   structureName: {
      color: '#FFF',
      fontSize: 16,
      fontWeight: '700',
   },
   structureAddress: {
      color: 'rgba(255,255,255,0.5)',
      fontSize: 12,
      marginTop: 2,
   },
   structureCoords: {
      color: 'rgba(255,255,255,0.3)',
      fontSize: 12,
      fontFamily: Platform.OS === 'ios' ? 'Menlo' : 'monospace',
      marginTop: 4,
   },
   structureCallBtn: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
      backgroundColor: 'rgba(48,209,88,0.1)',
      paddingHorizontal: 14,
      paddingVertical: 8,
      borderRadius: 10,
      borderWidth: 1,
      borderColor: 'rgba(48,209,88,0.2)',
   },
   structureCallText: {
      color: '#30D158',
      fontSize: 13,
      fontWeight: '600',
   },
   transportBottomPanel: {
      backgroundColor: colors.mainBackground,
      borderTopLeftRadius: 20,
      borderTopRightRadius: 20,
      marginTop: -16,
   },
   mapAddressOverlay: {
      position: "absolute",
      bottom: 0,
      left: 0,
      right: 0,
      backgroundColor: "rgba(0,0,0,0.8)",
      padding: 12,
      flexDirection: "row",
      alignItems: "flex-start",
      gap: 8,
   },
   mapAddressOverlayLabel: {
      fontSize: 12,
      fontWeight: "800",
      color: "rgba(255,255,255,0.45)",
      letterSpacing: 1,
      marginBottom: 4,
      textTransform: "uppercase",
   },
   smallAddressText: {
      color: "rgba(255,255,255,0.9)",
      fontSize: 13,
      fontWeight: "600",
      lineHeight: 18,
   },
   arrivalFooter: {
      flexDirection: "row",
      alignItems: "center",
      backgroundColor: "#0A0A0A",
      paddingHorizontal: 20,
      paddingVertical: 16,
      borderTopWidth: 1,
      borderColor: "rgba(255,255,255,0.05)",
      gap: 16,
   },
   footerTimerBox: { flex: 1 },
   footerTimerVal: { color: "#FFF", fontSize: 24, fontWeight: "900" },
   footerTimerLab: {
      color: "rgba(255,255,255,0.3)",
      fontSize: 10,
      fontWeight: "900",
      marginTop: 2,
   },
   footerBtn: {
      flex: 1.5,
      height: 56,
      borderRadius: 16,
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "center",
      gap: 8,
   },
   footerBtnText: { color: "#FFF", fontSize: 14, fontWeight: "900" },
   assessmentMainCard: {
      backgroundColor: "#1A1A1A",
      borderRadius: 32,
      padding: 8,
      borderWidth: 1,
      borderColor: "rgba(255,255,255,0.05)",
      marginBottom: 20,
   },
   assessmentRow: {
      flexDirection: "row",
      alignItems: "center",
      padding: 5,
      gap: 15,
   },
   assessmentIconBox: {
      width: 44,
      height: 44,
      borderRadius: 14,
      backgroundColor: "rgba(255,255,255,0.03)",
      justifyContent: "center",
      alignItems: "center",
   },
   assessmentRowTitle: {
      color: "rgba(255,255,255,0.4)",
      fontSize: 13,
      fontWeight: "900",
      letterSpacing: 1,
   },
   assessmentRowSub: {
      color: "#FFF",
      fontSize: 14,
      fontWeight: "700",
      marginTop: 2,
   },
   miniToggleGroup: {
      flexDirection: "row",
      gap: 8,
      backgroundColor: "#000",
      padding: 4,
      borderRadius: 12,
   },
   miniToggle: {
      paddingHorizontal: 16,
      paddingVertical: 8,
      borderRadius: 10,
      borderWidth: 1,
      borderColor: "transparent",
   },
   miniToggleActive: {
      backgroundColor: colors.secondary + "20",
      borderColor: colors.secondary,
   },
   miniToggleCrit: {
      backgroundColor: colors.primary + "20",
      borderColor: colors.primary,
   },
   miniToggleText: {
      color: "rgba(255,255,255,0.3)",
      fontSize: 13,
      fontWeight: "900",
   },
   miniToggleTextActive: { color: colors.secondary },
   miniToggleTextCrit: { color: colors.primary },
   sectionHeader: {
      color: "rgba(255,255,255,0.3)",
      fontSize: 13,
      fontWeight: "900",
      letterSpacing: 1.5,
      marginBottom: 16,
      marginLeft: 4,
   },
   severityGrid: { flexDirection: "row", gap: 10, marginBottom: 20 },
   severityItem: {
      flex: 1,
      backgroundColor: "#1A1A1A",
      borderRadius: 24,
      paddingVertical: 20,
      alignItems: "center",
      borderWidth: 2,
      borderColor: "transparent",
      gap: 8,
   },
   severityItemText: {
      fontSize: 13,
      fontWeight: "900",
      color: "rgba(255,255,255,0.3)",
   },
   smartAlertBox: {
      backgroundColor: colors.primary,
      borderRadius: 20,
      padding: 16,
      flexDirection: "row",
      alignItems: "center",
      gap: 12,
      marginTop: 10,
      marginBottom: 30,
   },
   smartAlertBoxText: {
      color: "#FFF",
      fontSize: 13,
      fontWeight: "900",
      flex: 1,
   },
   aidGrid: {
      flexDirection: "row",
      flexWrap: "wrap",
      gap: 16,
      justifyContent: "center",
      paddingBottom: 20,
   },
   aidCardGrid: {
      width: (SCREEN_WIDTH - 64) / 2, // 2 columns with 16px gap and 24px parent padding
      height: (SCREEN_WIDTH - 64) / 2 * 0.85, // Balanced aspect ratio
      backgroundColor: "#161616",
      borderRadius: 24,
      paddingVertical: 18,
      paddingHorizontal: 12,
      alignItems: "center",
      justifyContent: "center",
      borderWidth: 1.5,
      borderColor: "rgba(255,255,255,0.06)",
   },
   aidIconWrapper: {
      width: 52,
      height: 52,
      borderRadius: 16,
      backgroundColor: "rgba(255,255,255,0.04)",
      justifyContent: "center",
      alignItems: "center",
      marginBottom: 12,
   },
   aidLabelGrid: {
      color: "rgba(255,255,255,0.55)",
      fontSize: 14,
      fontWeight: "800",
      textAlign: "center",
      lineHeight: 18,
   },
   aidCheckBadge: {
      position: "absolute",
      top: 12,
      right: 12,
      width: 18,
      height: 18,
      borderRadius: 9,
      backgroundColor: colors.secondary,
      justifyContent: "center",
      alignItems: "center",
   },
   decisionGrid: {
      flexDirection: "row",
      justifyContent: "space-between",
      marginTop: 20,
      gap: 8,
   },
   decisionCardGrid: {
      width: (SCREEN_WIDTH - 64) / 2,
      height: (SCREEN_WIDTH - 64) / 2 * 1.1,
      backgroundColor: "#161616",
      borderRadius: 24,
      paddingVertical: 20,
      paddingHorizontal: 8,
      alignItems: "center",
      justifyContent: "center",
      borderWidth: 1.5,
      borderColor: "rgba(255,255,255,0.06)",
   },
   assessmentCard: {
      flex: 1,
      backgroundColor: "#161616",
      borderRadius: 24,
      paddingVertical: 18,
      paddingHorizontal: 12,
      alignItems: "center",
      borderWidth: 1,
      borderColor: "rgba(255,255,255,0.06)",
   },
   decisionIconBox: {
      width: 52,
      height: 52,
      borderRadius: 16,
      justifyContent: "center",
      alignItems: "center",
      marginBottom: 14,
   },
   decisionLabel: {
      color: "#FFF",
      fontSize: 15,
      fontWeight: "900",
      textAlign: "center",
   },
   bottomActionFixed: {
      position: 'absolute',
      bottom: 0,
      left: 0,
      right: 0,
      backgroundColor: '#000',
      paddingBottom: Platform.OS === 'ios' ? 34 : 24,
      paddingTop: 16,
      paddingHorizontal: 20,
      borderTopWidth: 1,
      borderColor: 'rgba(255,255,255,0.08)',
   },
   bottomActionFixedRow: {
      flexDirection: 'row',
      gap: 12,
      alignItems: 'center',
   },
   bottomCallBtn: {
      flex: 1,
      height: 60,
      borderRadius: 18,
      backgroundColor: 'rgba(255,255,255,0.06)',
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 12,
      borderWidth: 1,
      borderColor: 'rgba(255,255,255,0.08)',
   },
   bottomCallText: {
      color: '#FFF',
      fontSize: 15,
      fontWeight: '900',
   },
   bottomCallSub: {
      color: 'rgba(255,255,255,0.4)',
      fontSize: 11,
      fontWeight: '600',
      marginTop: 1,
   },
   bottomActionBtnPrimary: {
      flex: 1.4,
      height: 60,
      borderRadius: 18,
      backgroundColor: colors.secondary,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 10,
   },
   bottomActionBtnPrimaryText: {
      color: '#000',
      fontSize: 14,
      fontWeight: '900',
      letterSpacing: 0.5,
   },
   choiceModalOverlay: {
      flex: 1,
      backgroundColor: 'rgba(0,0,0,0.85)',
      justifyContent: 'flex-end',
   },
   choiceModalContent: {
      backgroundColor: '#1A1A1A',
      borderTopLeftRadius: 32,
      borderTopRightRadius: 32,
      padding: 24,
      paddingBottom: Platform.OS === 'ios' ? 44 : 34,
   },
   choiceModalHeader: {
      fontSize: 20,
      fontWeight: '900',
      color: '#FFF',
      marginBottom: 24,
      textAlign: 'center',
   },
   choiceBtn: {
      height: 64,
      borderRadius: 20,
      backgroundColor: 'rgba(255,255,255,0.05)',
      flexDirection: 'row',
      alignItems: 'center',
      paddingHorizontal: 20,
      marginBottom: 12,
      gap: 16,
   },
   choiceBtnText: {
      flex: 1,
      color: '#FFF',
      fontSize: 17,
      fontWeight: '700',
   },
   choiceCancelBtn: {
      height: 64,
      borderRadius: 20,
      alignItems: 'center',
      justifyContent: 'center',
      marginTop: 8,
   },
   choiceCancelText: {
      color: 'rgba(255,255,255,0.5)',
      fontSize: 17,
      fontWeight: '700',
   },
   hospitalResultCard: {
      backgroundColor: "#111",
      borderRadius: 30,
      padding: 40,
      alignItems: "center",
      borderWidth: 1,
      borderColor: colors.secondary,
   },
   hospResTitle: {
      color: "#FFF",
      fontSize: 22,
      fontWeight: "900",
      marginTop: 20,
      textAlign: "center",
   },
   hospResDetail: { color: "rgba(255,255,255,0.4)", fontSize: 14, marginTop: 8 },
   hospResBadge: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 5,
      backgroundColor: colors.secondary + "15",
      paddingHorizontal: 12,
      paddingVertical: 6,
      borderRadius: 10,
   },
   hospResBadgeText: {
      color: colors.secondary,
      fontSize: 12,
      fontWeight: "900",
   },
   transportChoiceCard: {
      height: 100,
      backgroundColor: "#111",
      borderRadius: 25,
      flexDirection: "row",
      alignItems: "center",
      padding: 25,
      gap: 20,
      borderWidth: 1,
      borderColor: "rgba(255,255,255,0.05)",
   },
   transportChoiceTitle: { color: "#FFF", fontSize: 18, fontWeight: "900" },
   closureView: {
      flex: 1,
      justifyContent: "center",
      alignItems: "center",
      padding: 40,
   },
   successHalo: {
      width: 100,
      height: 100,
      borderRadius: 40,
      backgroundColor: colors.secondary + "15",
      justifyContent: "center",
      alignItems: "center",
      marginBottom: 40,
   },
   closureTitle: {
      fontSize: 32,
      fontWeight: "900",
      color: "#FFF",
      marginBottom: 15,
      textAlign: "center",
   },
   closureSubtitle: {
      fontSize: 16,
      color: colors.textMuted,
      textAlign: "center",
      lineHeight: 24,
   },
   largeReturnBtn: {
      backgroundColor: colors.secondary,
      height: 64,
      paddingHorizontal: 40,
      borderRadius: 32,
      justifyContent: "center",
      alignItems: "center",
      marginTop: 40,
   },
   largeReturnBtnText: {
      color: "#FFF",
      fontSize: 16,
      fontWeight: "900",
      letterSpacing: 1,
   },
   timelineSidebar: {
      flex: 0.8,
      backgroundColor: "#0A0A0A",
      borderTopWidth: 1,
      borderColor: "rgba(255,255,255,0.08)",
   },
   timelineContainer: {
      flex: 1,
      padding: 20,
   },
   timelineHeader: {
      color: "rgba(255,255,255,0.3)",
      fontSize: 13,
      fontWeight: "900",
      marginBottom: 15,
      letterSpacing: 1.5,
      textTransform: "uppercase",
   },
   timelineItem: { flexDirection: "row", gap: 15, marginBottom: 20 },
   timelinePointRow: { alignItems: "center" },
   timelineLine: {
      position: "absolute",
      top: 20,
      bottom: -20,
      width: 1,
      backgroundColor: "rgba(255,255,255,0.05)",
   },
   timelineIconBox: {
      width: 28,
      height: 28,
      borderRadius: 14,
      justifyContent: "center",
      alignItems: "center",
   },
   timelineContent: { flex: 1 },
   timelineTextRow: { flexDirection: "row", alignItems: "center", gap: 8 },
   timelineTime: {
      color: "rgba(255,255,255,0.3)",
      fontSize: 14,
      fontWeight: "900",
   },
   timelineLabel: { color: "#FFF", fontSize: 15, fontWeight: "700" },
   itemStatusBadge: {
      backgroundColor: "rgba(255,255,255,0.05)",
      alignSelf: "flex-start",
      paddingHorizontal: 8,
      paddingVertical: 4,
      borderRadius: 6,
      marginTop: 4,
   },
   itemStatusText: { color: colors.secondary, fontSize: 12, fontWeight: "900" },
   floatingInfoContainer: {
      position: 'absolute',
      bottom: 20,
      left: 20,
      right: 20,
      alignItems: 'center',
      zIndex: 100,
   },
   tacticalCard: {
      width: '100%',
      backgroundColor: 'rgba(20, 20, 20, 0.95)',
      borderRadius: 24,
      padding: 16,
      borderWidth: 1,
      borderColor: 'rgba(255, 255, 255, 0.1)',
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 10 },
      shadowOpacity: 0.5,
      shadowRadius: 20,
      elevation: 10,
   },
   cardHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      marginBottom: 16,
   },
   statusDot: {
      width: 6,
      height: 6,
      borderRadius: 3,
      marginRight: 10,
   },
   unitName: {
      color: '#FFF',
      fontSize: 16,
      fontWeight: '700',
   },
   caseRef: {
      color: 'rgba(255, 255, 255, 0.4)',
      fontSize: 11,
      fontWeight: '700',
      textTransform: 'uppercase',
   },
   statsRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      backgroundColor: 'rgba(255, 255, 255, 0.03)',
      borderRadius: 16,
      padding: 12,
      marginBottom: 12,
   },
   statItem: {
      flex: 1,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
   },
   statDivider: {
      width: 1,
      height: 24,
      backgroundColor: 'rgba(255, 255, 255, 0.1)',
      marginHorizontal: 12,
   },
   statLabel: {
      color: 'rgba(255, 255, 255, 0.4)',
      fontSize: 9,
      fontWeight: '800',
      letterSpacing: 0.5,
   },
   statValue: {
      color: '#FFF',
      fontSize: 14,
      fontWeight: '700',
   },
   // HOSPITAL SELECTION STYLES
   hospitalList: { marginTop: 10, paddingBottom: 100 },
   hospitalCard: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: '#161616',
      borderRadius: 18,
      padding: 16,
      marginBottom: 12,
      borderWidth: 1,
      borderColor: 'rgba(255,255,255,0.08)',
      gap: 16,
   },
   hospitalCardActive: {
      borderColor: colors.secondary,
      backgroundColor: colors.secondary + '10',
   },
   hospitalIconBox: {
      width: 44,
      height: 44,
      borderRadius: 14,
      backgroundColor: 'rgba(255,255,255,0.04)',
      justifyContent: 'center',
      alignItems: 'center',
   },
   hospitalCardInfo: { flex: 1 },
   hospitalCardName: {
      color: '#FFF',
      fontSize: 16,
      fontWeight: '800',
      marginBottom: 4,
   },
   hospitalCardStats: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 12,
   },
   hospitalStatItem: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 4,
   },
   hospitalStatText: {
      color: 'rgba(255,255,255,0.4)',
      fontSize: 12,
      fontWeight: '700',
   },
   selectHospBtn: {
      backgroundColor: colors.secondary,
      paddingHorizontal: 16,
      paddingVertical: 10,
      borderRadius: 12,
   },
   selectHospBtnText: {
      color: '#FFF',
      fontSize: 13,
      fontWeight: '900',
   },
   hospitalsLoadingContainer: {
      paddingVertical: 40,
      alignItems: 'center',
      justifyContent: 'center',
   },
   hospitalsEmptyContainer: {
      paddingVertical: 40,
      alignItems: 'center',
      justifyContent: 'center',
   },
   hospitalsEmptyText: {
      color: 'rgba(255,255,255,0.4)',
      fontSize: 14,
      textAlign: 'center',
      lineHeight: 20,
   }
});
